name: 'Martini Upload Package'
description: 'Prepares and uploads packages to a Martini instance'
author: 'Rafal Janicki <rafal.janicki@torocloud.com>'

inputs:
  base_url:
    description: 'Base URL of the Martini instance'
    required: true
  access_token:
    description: 'Access token of the Martini instance'
    required: true
  package_dir:
    description: 'Path to the directory containing package folders'
    required: false
    default: 'packages'
  package_name_pattern:
    description: 'Regex pattern to match package directories'
    required: false
    default: '.*'
  async_upload:
    description: 'Enable async upload'
    required: false
    default: 'false'
  success_check_timeout:
    description: 'Timeout for success check in seconds'
    required: false
    default: '6'
  success_check_delay:
    description: 'Delay between success checks in seconds'
    required: false
    default: '30'
  success_check_package_name:
    description: 'Name of the package to check for success'
    required: false
    default: ''

outputs:
  packages:
    description: 'List of uploaded packages with id, name, status, and version'

runs:
  using: 'node20'
  main: 'dist/index.js'